//USER REDUDERS
export const USER_ERROR = "USER_ERROR";



//SIGNIN
export const SET_FORGOTPASSWORD = "SET_FORGOTPASSWORD";
export const SET_SENT = "SET_SENT";


//CAROUSEL
export const SET_TITLE = "SET_TITLE";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_IMAGE = "SET_IMAGE";
export const SET_IMAGE_NAME = "SET_IMAGE_NAME";
export const SET_CAROUSEL = "SET_CAROUSEL";
export const SET_CAROUSEL_COUNT = "SET_CAROUSEL_COUNT";
export const SET_CAROUSEL_UID = "SET_CAROUSEL_UID";
export const SET_ADD = "SET_ADD";
export const SET_EDIT = "SET_EDIT";
export const SET_DELETE = "SET_DELETE";
export const SET_CONFIRM_DELETE = "SET_CONFIRM_DELETE";
export const SET_SELECTED_CAROUSEL = "SET_SELECTED_CAROUSEL";
export const SET_SELECTED = "SET_SELECTED";
export const SET_CONFIRM_SIGNOUT = "SET_CONFIRM_SIGNOUT";

//ACCOUNT
export const SET_ACCOUNT_ADD = "SET_ACCOUNT_ADD";
export const SET_ACCOUNT_ADD_MODAL = "SET_ACCOUNT_ADD_MODAL";